
server:
  port: ${SERVER_PORT:8081}
logging:
  level:
    root: INFO
    com:
      example: DEBUG
  file:
    name: klasha-assessment.log
  logback:
    rollingpolicy:
      max-file-size: 60MB
klasha:
  cities:
    domain: ${DOMAIN:https://countriesnow.space}
    base-url: ${BASE_URL:https://countriesnow.space/api/v0.1/countries}
    states-url: ${STATES_URL:${klasha.cities.base-url}/states}
    population-url: ${POPULATION_URL:${klasha.cities.base-url}/population}
    capital-url: ${POPULATION_URL:${klasha.cities.base-url}/capital}
    location-url: ${POPULATION_URL:${klasha.cities.base-url}/positions}
    currency-url: ${POPULATION_URL:${klasha.cities.base-url}/currency}

